services:
  - type: web
    name: mystical-monsters-rewards-api
    runtime: node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
